### PR TITLE
Bump v31.0.1

### PR DESCRIPTION
**Pull request by leplatrem**
* [x] Confirm that signatures are valid in DEV using devtools

### CODE REVIEW

**Comment by grahamalama** [comment]
Did we
> Confirm that signatures are valid in DEV using devtools
?

**Comment by leplatrem** [comment]
There aren't signatures anymore in DEV.

The Remote Settings Devtools UI shows a warning because the timestsamps from monitor/changes don't match. This is not great, although it's only visual and easy to fix.

**Review by grahamalama — APPROVED** [review]

**Comment by leplatrem** [comment]
> This is not great, although it's only visual and easy to fix.

Actually, not so easy. The value shown as `server timestamp` in the DevTools comes from a call that is made by the client itself using `await RemoteSettings.inspect()`
https://searchfox.org/mozilla-central/rev/fb9a504ca73529fa550efe488db2a012a4bf5169/services/settings/remote-settings.js#509

We can either:

Change the client code of `inspect()` (must ride trains) etc.:
```diff
- const { bucket, collection, last_modified: serverTimestamp } = change;
+ const { bucket, collection, last_publication: serverTimestamp } = change;
```

Or change the DevTools code, to fetch the list of changes from the server instead of relying on `inspect()`. 

Or change the DevTools code, to just remove this warning.

I would vote to postpone the deployment of this v31 version in STAGE & PROD, until we have a new version of the DevTools released with a fix. Otherwise it could be relatively confusing for QA to see synchronization warnings when everything is actually up-to-date and successful.

**Comment by leplatrem** [comment]
I will reopen a similar release PR after https://github.com/mozilla/remote-settings/pull/354 is merged

**Pull request closed without merging**
